pastmlapp/urls.py
from django.conf.urls import url

from pastmlapp import views

app_name = "pastmlapp"

urlpatterns = [
    url(r'^run$', views.pastml, name='pastml'),
    url(r'^$', views.index, name='index'),
    url(r'^run/(?P<id>[\w\d-]+)$', views.analysis, name='analysis'),
    url(r'^result_full/(?P<id>[\w\d-]+)$', views.result_full, name='result_full'),
    url(r'^result/(?P<id>[\w\d-]+)$', views.result, name='result'),
    url(r'^view/(?P<id>[\w\d-]+)$', views.detail, name='detail'),
    url(r'^view_full/(?P<id>[\w\d-]+)$', views.detail_full, name='detail_full'),
    url(r'^feedback$', views.feedback, name='feedback'),
    url(r'^help$', views.helppage, name='help'),
    url(r'^cite$', views.cite, name='cite'),
    url(r'^install$', views.install, name='install'),
]

pastmlweb/urls.py
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    url(r'^', include('pastmlapp.urls', namespace="pastmlapp")),
    path('admin/', admin.site.urls),
]

pastmlapp/forms.py
from collections import OrderedDict

import pandas as pd
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS
from django.forms import ModelForm, widgets
from multiselectfield import MultiSelectFormField
from pastml.acr import parse_date
from pastml.ml import is_ml
from pastml.tree import read_forest, read_tree

from pastmlapp.models import TreeData, Analysis, Column

MAX_N_TREES = 5


# Create the form class.
class TreeDataForm(ModelForm):
    error_css_class = "error"

    class Meta:
        model = TreeData
        fields = ['tree', 'data', 'data_sep']
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }

        widgets = {
            'data': forms.FileInput(attrs={'id': 'csv'}),
            'tree': forms.FileInput(attrs={'id': 'nwk'})
        }

    def clean(self):
        cleaned_data = super().clean()

        sep = cleaned_data.get('data_sep', '\t')
        if not sep or sep == '<tab>':
            self.cleaned_data['data_sep'] = '\t'
            sep = '\t'

        f = cleaned_data.get('tree', None)
        if f:
            f = f.file  # the file in Memory
            try:
                nwks = f.read().decode().replace('\n', '').split(';')
                if not nwks:
                    self.add_error('tree',
                                   u'Could not find any trees (in Newick format) in the file.')
                else:
                    n_trees = len([read_tree(nwk + ';') for nwk in nwks[:-1]])
                    if n_trees > MAX_N_TREES:
                        self.add_error('tree',
                                       u'The file contains too many trees ({}), the limit is {}.'
                                       .format(n_trees, MAX_N_TREES))
            except:
                self.add_error('tree',
                               u'Your tree does not seem to be in Newick format.')

        f = cleaned_data.get('data', None)
        if f:
            f = f.file
            try:
                df = pd.read_table(f, sep=sep, header=0)
                if len(df.columns) < 2:
                    get_col_name = lambda _: '"{}..."'.format(_[:10]) if len(_) > 10 else '"{}"'.format(_)
                    self.add_error('data', u'Your annotation table contains {} column: {}, '
                                           u'while it must contain at least 2: tip ids and their states. '
                                           u'Please check if the separator ("{}") is correct.'
                                   .format(len(df.columns), ', '.join(get_col_name(_) for _ in df.columns),
                                           '<tab>' if sep == '\t' else sep))
            except:
                self.add_error('data', u'We could not parse your annotation table, '
                                       u'please check if the separator ("{}") is correct.'
                               .format('<tab>' if sep == '\t' else sep))
        return cleaned_data


class AnalysisForm(ModelForm):
    error_css_class = "error"

    class Meta:
        model = Analysis
        fields = ['prediction_method', 'model', 'root_date', 'timeline_type', 'no_trimming']#, 'email', 'title']

    def __init__(self, data=None, *args, **kwargs):
        super(AnalysisForm, self).__init__(data, *args, **kwargs)
        td = TreeData.objects.get(pk=self.instance.tree_data.id)
        self.column_choices = tuple((str(_), str(_))
                                    for _ in pd.read_table(td.data.path, sep=td.data_sep, header=0).columns)

        self.fields['tip_id_column'] = forms.ChoiceField(required=True, choices=self.column_choices,
                                                         help_text=u'Column containing tip ids '
                                                                   u'(in the same format as in the tree).')

        multi_column = len(self.column_choices) > 2

        self.fields['character_column(s)' if multi_column else 'character_column'] = \
            MultiSelectFormField(choices=self.column_choices, max_choices=6, min_choices=1,
                                 help_text=u'Column(s) whose ancestral states are to be reconstructed '
                                           u'(to select multiple columns keep Shift pressed).',
                                 widget=widgets.SelectMultiple) \
                if multi_column else \
                forms.ChoiceField(required=True, choices=self.column_choices,
                                  help_text=u'Column whose ancestral states are to be reconstructed.',
                                  initial=self.column_choices[1])

        self.fields.keyOrder = ['tip_id_column', 'character_column{}'.format('(s)' if multi_column else ''),
                                'prediction_method', 'model', 'root_date', 'timeline_type', 'no_trimming'] #, 'email', 'title']
        self.fields = OrderedDict((k, self.fields[k]) for k in self.fields.keyOrder)

    def clean_prediction_method(self):
        m = self.cleaned_data['prediction_method']
        if not is_ml(m):
            self.fields['model'].required = False
        return m

    def clean_root_date(self):
        root_date = self.cleaned_data.get('root_date', None)
        if root_date:
            try:
                root_dates = [_.strip(' ') for _ in root_date.replace('\t', ' ').split(' ') if _.strip(' ')]
                n_dates = len([parse_date(_) for _ in root_dates])
                n_trees = len(read_forest(TreeData.objects.get(pk=self.instance.tree_data.id).tree.path))
                if 1 < n_dates < n_trees:
                    self.add_error('root_date',
                                   u'Not enough dates for your {} trees.'.format(n_trees))
                root_date = ' '.join(root_dates)
            except ValueError:
                self.add_error('root_date',
                               u'Your root date format is invalid, please use YYYY-mm-dd or float.')
        return root_date

    def save(self, commit=True):
        self.cleaned_data['id_column'] = next(i for (i, (c, _)) in enumerate(self.column_choices)
                                              if c == self.cleaned_data['tip_id_column'])
        super(AnalysisForm, self).save(commit=commit)
        analysis = self.instance

        for _ in self.cleaned_data["character_column(s)"] if "character_column(s)" in self.cleaned_data \
                else [self.cleaned_data['character_column']]:
            Column.objects.create(
                analysis=analysis,
                column=_,
            )

pastmlapp/views.py
import os
from django.contrib.sites.models import Site
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from pastml.ml import F81, is_ml
from pastml.tree import read_forest

from pastmlapp.forms import TreeDataForm, AnalysisForm
from pastmlapp.models import TreeData, Analysis, Column
from .tasks import apply_pastml


def result(request, id):
    analysis = get_object_or_404(Analysis, pk=id)
    data = 'Could not load ancestral character reconstruction {}'.format(id)
    try:
        with open(analysis.html_compressed, 'r') as f:
            data = f.read()
    except:
        pass
    return render(request, 'pastmlapp/result.html', {'text': data})


def result_full(request, id):
    analysis = get_object_or_404(Analysis, pk=id)
    data = 'Could not load full tree visualisation for {} (probably your tree is too big).'.format(id)
    try:
        with open(analysis.html_compressed.replace('.compressed.html', '.full.html'), 'r') as f:
            data = f.read()
    except:
        pass
    return render(request, 'pastmlapp/result.html', {'text': data})


def detail(request, id):
    analysis = get_object_or_404(Analysis, pk=id)
    if os.path.exists(analysis.html_compressed):
        columns = [column.column for column in Column.objects.filter(
                analysis=analysis
            )]
        context = {'id': id, 'model': analysis.model if is_ml(analysis.prediction_method) else None,
                   'prediction_method': analysis.prediction_method,
                   'columns': ', '.join(columns)}
        # itol_id_file = os.path.join(os.path.dirname(analysis.html_compressed), 'pastml_{}_itol.txt'.format(id))
        # if os.path.exists(itol_id_file):
        #     with open(itol_id_file, 'r') as f:
        #         context['itol'] = f.readline().strip('\n')
        if os.path.exists(analysis.html_compressed.replace('.compressed.html', '.full.html')):
            context['other_html'] = 1

        if not os.path.exists(analysis.html_compressed.replace('{}.compressed.html'.format(analysis.id),
                                                               'pastml_{}.zip'.format(analysis.id))):
            context['rec_error'] = True

    else:
        context = {}
    return render(request, 'pastmlapp/layout.html', {
        'title': 'Results',
        'content': render_to_string('pastmlapp/detail.html', request=request, context=context)
    })


def detail_full(request, id):
    analysis = get_object_or_404(Analysis, pk=id)
    if os.path.exists(analysis.html_compressed):
        columns = [column.column for column in Column.objects.filter(
                analysis=analysis
            )]
        context = {'id': id, 'full': 1, 'model': analysis.model if is_ml(analysis.prediction_method) else None,
                   'prediction_method': analysis.prediction_method,
                   'columns': ', '.join(columns)}
        if not os.path.exists(analysis.html_compressed.replace('{}.compressed.html'.format(analysis.id),
                                                               'pastml_{}.zip'.format(analysis.id))):
            context['rec_error'] = True

    else:
        context = {}
    return render(request, 'pastmlapp/layout.html', {
        'title': 'Results',
        'content': render_to_string('pastmlapp/detail.html', request=request, context=context)
    })


def index(request):
    if request.method == 'POST':
        return redirect('pastmlapp:pastml')
    return render(request, 'pastmlapp/layout.html', {
        'title': 'PastML',
        'content': render_to_string('pastmlapp/index.html')
    })


def pastml(request):
    if request.method == 'POST':
        tree_data = TreeData()
        form = TreeDataForm(instance=tree_data, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('pastmlapp:analysis', id=tree_data.id)
    else:
        form = TreeDataForm

    return render(request, 'pastmlapp/layout.html', {
        'title': 'Run PastML',
        'content': render_to_string('pastmlapp/pastml.html', request=request, context={
            'form': form
        })
    })


def analysis(request, id):
    tree_data = TreeData.objects.get(pk=id)
    analysis = Analysis(tree_data=tree_data)

    if request.method == 'POST':
        form = AnalysisForm(instance=analysis, data=request.POST)
        if form.is_valid():
            form.save()

            tree = tree_data.tree.path
            wd = os.path.dirname(tree)

            html_compressed = os.path.join(wd, '{}.compressed.html'.format(analysis.id))

            columns = [column.column for column in Column.objects.filter(
                analysis=analysis
            )]
            analysis.html_compressed = html_compressed
            analysis.save()

            work_dir = os.path.join(wd, 'pastml_{}'.format(analysis.id))

            html = os.path.join(wd, '{}.full.html'.format(analysis.id)) \
                if sum(len(_) for _ in read_forest(tree)) <= 1000 else None

            root_date = form.cleaned_data['root_date'] \
                if 'root_date' in form.cleaned_data and form.cleaned_data['root_date'] else None
            if root_date is not None:
                root_date = root_date.split(' ')
            apply_pastml.delay(id=analysis.id, data=tree_data.data.path, tree=tree,
                               data_sep=tree_data.data_sep if tree_data.data_sep and tree_data.data_sep != '<tab>' else '\t',
                               id_index=form.cleaned_data['id_column'], columns=columns,
                               root_date=root_date,
                               model=form.cleaned_data['model'] if 'model' in form.cleaned_data and form.cleaned_data['model'] else F81,
                               prediction_method=form.cleaned_data['prediction_method'],
                               name_column=columns[0], html_compressed=html_compressed, html=html, email=None,
                               title='', url=Site.objects.get_current(request=request).domain,
                               work_dir=work_dir, no_trimming=form.cleaned_data['no_trimming'],
                               timeline_type=form.cleaned_data['timeline_type'])

            return redirect('pastmlapp:detail', id=analysis.id)
    else:
        form = AnalysisForm(instance=analysis)

    return render(request, 'pastmlapp/layout.html', {
        'title': 'Run PastML',
        'content': render_to_string('pastmlapp/analysis.html', request=request, context={
            'form': form
        })
    })


def feedback(request):
    return render(request, 'pastmlapp/layout.html', {
        'title': 'Contact us',
        'content': render_to_string('pastmlapp/feedback.html')
    })


def helppage(request):
    return render(request, 'pastmlapp/layout.html', {
        'title': 'PastML How To',
        'content': render_to_string('pastmlapp/help.html')
    })


def cite(request):
    return render(request, 'pastmlapp/layout.html', {
        'title': 'Cite PastML',
        'content': render_to_string('pastmlapp/cite.html')
    })


def install(request):
    return render(request, 'pastmlapp/layout.html', {
        'title': 'Install PastML locally',
        'content': render_to_string('pastmlapp/install.html')
    })

templates/pastmlapp/analysis.html
{% if error %}
<p class="has-error">{{ error }}</p>
{% endif %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if form.non_field_errors %}
            <div class="nf-error">
            <ul class="errorlist">
                {% for error in fform.non_field_errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            </div>
        {% endif %}
    {% for field in form %}
        {% if field.errors %}
      <div class="field error">
            <ul class="errorlist">
                {% for error in field.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% else %}
      <div class="field">
        {% endif %}
          <p>
            <label class="mylabel">{{ field.label }}</label>
            {{ field }}
            <span class="helptext">{{ field.help_text|safe}}</span>
        </p>
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Reconstruct ancestral states</button>
  </form>

<p class="help-ref"><i>(You can learn more about ancestor character prediction methods <a href="{% url 'pastmlapp:help' %}#acr" target="_blank">here</a>.)</i></p>

<script>

    function adjustModelToMethod(pm) {
        var m = document.getElementById("id_model");
        if (pm.value != "MPPA" && pm.value !="MAP" && pm.value != "JOINT" && pm.value != "ML" && pm.value != "ALL") {
            m.disabled = true;
            m.parentNode.style.opacity = "0.5";
        } else {
            m.disabled = false;
            m.parentNode.style.opacity = "1";
        }
    }

    var pm = document.getElementById('id_prediction_method');
    adjustModelToMethod(pm);
    pm.onchange = function () {
        adjustModelToMethod(this);
    }

    <!--function adjustTitleToEmail(e) {-->
        <!--var t = document.getElementById("id_title");-->
        <!--if (e.value && e.value != "") {-->
            <!--t.disabled = false;-->
            <!--t.parentNode.style.opacity = "1";-->
        <!--} else {-->
            <!--t.disabled = true;-->
            <!--t.parentNode.style.opacity = "0.5";-->
        <!--}-->
    <!--}-->

    <!--var e = document.getElementById('id_email');-->
    <!--adjustTitleToEmail(e);-->
    <!--e.onchange = function () {-->
        <!--adjustTitleToEmail(this);-->
    <!--}-->
</script>
{% endblock %}

templates/pastmlapp/cite.html
<div id="content">
<h2>Cite PastML</h2>
<p>If you find PastML useful, please cite it as:
    Ishikawa SA, Zhukova A, Iwasaki W, Gascuel O (2019) <b>A Fast Likelihood Method to Reconstruct and Visualize Ancestral Scenarios</b>. <a href="https://doi.org/10.1093/molbev/msz131" target="_blank"><i>Molecular Biology and Evolution</i>, msz131</a>.</p>

    <p>The data described in the article above are available
        <a href="https://github.com/evolbioinfo/pastml/tree/1.9.15/examples/DENV2" target="_blank">here (phylogeography of Dengue serotype 2 epidemics)</a>,
        <a href="https://github.com/evolbioinfo/pastml/tree/1.9.15/examples/HIV1C" target="_blank">here (drug resistance mutations in HIV-1C)</a>,
        and <a href="https://github.com/saishikawa/PASTML/tree/simulations/examples/simulation" target="_blank">here (simulation study)</a>.</p>
</div>

templates/pastmlapp/detail.html
{% if error %}
 <p class="error">{{ error }}</p>
{% elif id %}
 <h3>Ancestral reconstruction of {{columns}} (with {{prediction_method}} method{% if model %} and model {{model}}{% endif %})</h3>
{% if rec_error %}
 <p>Sorry, there was a problem with your reconstruction: </p>
{% endif %}

{% if full %}
  <p class="help-ref"><i>(You can view the compressed tree visualisation <a href="{% url 'pastmlapp:detail' id=id %}" target="_blank">here</a>.)</i></p>

  <div id="resizable">
    <iframe src="{% url 'pastmlapp:result_full' id=id %}"  width="100%" height="{% if rec_error %} 100 {% else %} 500 {% endif %}" id="vis" allowfullscreen></iframe>
  </div>
{% else %}
  {% if other_html %}
    <p class="help-ref"><i>(You can view the full tree visualisation <a href="{% url 'pastmlapp:detail_full' id=id %}" target="_blank">here</a>.)</i></p> <!--and at <a href="http://itol.embl.de/external.cgi?tree={{ itol }}" target="_blank">iTOL</a>.)</i></p>-->
  {% else %}
<!--    <p class="help-ref"><i>(You can view the full tree visualisation at <a href="http://itol.embl.de/external.cgi?tree={{ itol }}" target="_blank">iTOL</a>.)</i></p>-->
  {% endif %}
  <div id="resizable">
    <iframe src="{% url 'pastmlapp:result' id=id %}"  width="100%" height="{% if rec_error %} 100 {% else %} 500 {% endif %}" id="vis" allowfullscreen></iframe>
  </div>
{% endif %}
{% if rec_error %}
 <p class="help-ref"><i>Please, make sure that you tree and annotation data were <a href="{% url 'pastmlapp:help' %}#data" target="_blank">formatted properly</a>,
  and <a href="{% url 'pastmlapp:feedback' %}" target="_blank">let us know</a> about this issue.</i></p>
{% else %}
 <div class="info"><p><a href="/media/pastml_{{id}}.zip" class="btn btn-primary" download>Download</a><span class="helptext"> this visualisation and all the associated data.</span></p></div>
 <p class="help-ref"><i>(You can learn more about this visualisation <a href="{% url 'pastmlapp:help' %}#visualisation" target="_blank">here</a>.)</i></p>
{% endif %}

 <script type="text/javascript">
     $('#vis').css('height', $(window).height() +'px');
 </script>
{% else %}
 <head>
  <meta http-equiv="refresh" content="12">
 </head>
 {% load staticfiles %}
 <p> We are reconstructing and visualising the ancestral states... </p>
 <p> Once it is done, the result will appear on this page. </p>
 <image src="{% static 'img/steps_small.gif' %}" alt="PASTML steps gif"></image>
{% endif %}

templates/pastmlapp/feedback.html
{% block content %}
<p> If you have any problem, suggestion or comment about PastML, please submit an issue on PastML <a href="https://github.com/evolbioinfo/pastml/issues" target="_blank">GitHub</a>,<br/>or contact Anna at anna[dot]zhukova[at]pasteur[dot]fr.</p>
{% endblock %}

templates/pastmlapp/index.html
<div>
  <div style="float:right;">
    <img src="/static/img/full_pipeline.png" style="width:500px;"/>
  </div>
  <h2>About PastML</h2>
  <p>PastML infers ancestral characters on a rooted phylogenetic tree with annotated tips, using maximum likelihood or parsimony. The result is then visualised as a zoomable html map.</p>
  <p>To learn more about how PastML works, please visit our <a href="{% url 'pastmlapp:help' %}">Help page</a>.</p>
  <p>To learn even more, to cite PastML, or to see the data and simulations described in the article, see <a href="{% url 'pastmlapp:cite' %}">here</a>.</p>
  <p>To install PastML locally or use it via docker, follow <a href="{% url 'pastmlapp:install' %}">the installation instructions</a>.</p>
  <p>PastML source code is available on <a href="https://github.com/evolbioinfo/pastml" target="_blank">github</a>.</p>

  <h2>Cite PastML</h2>
  <p>Ishikawa SA, Zhukova A, Iwasaki W, Gascuel O (2019) <b>A Fast Likelihood Method to Reconstruct and Visualize Ancestral Scenarios</b>. <a href="https://doi.org/10.1093/molbev/msz131" target="_blank"><i>Molecular Biology and Evolution</i>, msz131</a>.</p>

  <h2>Try it now</h2>
  <p>You need two files to run PastML: </p>
  <ul>
    <li>a rooted tree, in <a href="https://en.wikipedia.org/wiki/Newick_format" target="_blank">Newick</a> format;</li>
    <li>an annotation table specifying tip states, in <a href="https://en.wikipedia.org/wiki/Comma-separated_values" target="_blank">CSV</a> format.</li>
  </ul>
  <a class="btn btn-primary" href="{% url 'pastmlapp:pastml' %}" role="button">Run PastML</a>

  <h2>Example data</h2>
  <p>If you prefer, try PastML on our example.<p>
  <h3>HIV-1A in Albania</h3>
  This data set comes from the study by
    <a href="https://doi.org/10.1093/bioinformatics/btt010" target="_blank">Chevenet&nbsp;<i>et&nbsp;al.</i>,&nbsp;2013</a>,
    which adopted the data from <a href="https://doi.org/10.1371/journal.pone.0001390" target="_blank">Salemi&nbsp;<i>et&nbsp;al.</i>,&nbsp;2008</a>, and includes:</p>
  <ul>
    <li>a rooted HIV-1A tree with 152 tips,</li>
    <li>a comma-separated annotation file describing the country of sampling for each tree tip.</li>
  </ul>
  <p>Check out the visualisation of the Albanian data phylogeography:
    <a href="{% url 'pastmlapp:detail' id='e1cef896-cba8-498b-8f82-e19339d3e7a6' %}" target="_blank">compressed visualisation</a>
    and <a href="{% url 'pastmlapp:detail_full' id='e1cef896-cba8-498b-8f82-e19339d3e7a6' %}" target="_blank">full tree visualisation</a>.</p>
  <a class="btn btn-primary" type="submit" onclick="window.open('/static/Albania.zip')" role="button">Download data</a>
</div>

templates/pastmlapp/install.html
<div id="content">
<h2>Install PastML</h2>

<p>PastML is a python3 module that provides fast Ancestor Character Reconstruction and visualisation methods.
    Its source code is available on <a href="https://github.com/evolbioinfo/pastml" target="_blank">github</a>.</p>
<p>PastML is also available via <a href="https://www.docker.com/community-edition" target="_blank">docker</a>
    as <a href="https://hub.docker.com/r/evolbioinfo/pastml/" target="_blank">evolbioinfo/pastml</a>.</p>


<h3>Installation</h3>
    <p>To install PastML follow the instructions <a href="https://github.com/evolbioinfo/pastml" target="_blank">here</a>.
        It can be used within Python 3, command line or via docker.</p>
</div>

templates/pastmlapp/pastml.html
{% if error %}
<p class="has-error">{{ error }}</p>
{% endif %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% if form.non_field_errors %}
            <div class="nf-error">
            <ul class="errorlist">
                {% for error in fform.non_field_errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            </div>
        {% endif %}
    {% for field in form %}
        {% if field.errors %}
      <div class="field error">
            <ul class="errorlist">
                {% for error in field.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% else %}
      <div class="field">
        {% endif %}
            <p>
            <label class="mylabel">{{ field.label }}</label>
            {{ field }}
            <span class="helptext">{{ field.help_text|safe}}</span>
        </p>
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

<p class="help-ref"><i>(You can learn more about input data <a href="{% url 'pastmlapp:help' %}#data" target="_blank">here</a>.)</i></p>

    <script type="text/javascript">
        $("#nwk").change(function(){
          $("#nwk").parent().parent().removeClass("error");
          $("#nwk").parent().parent().find("ul").remove();

        });
        $("#csv").change(function(){
          $("#csv").parent().parent().removeClass("error");
          $("#csv").parent().parent().find("ul").remove();
        });
    </script>
{% endblock %}

templates/pastmlapp/result.html
{{text|safe}}